version: '3'

services:

  mysql:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    container_name: mysql
    networks: 
      - net-mysql
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    networks: 
      - net-mysql
    environment:
      MYSQL_USER: "root"
      MYSQL_PASSWORD: "root"
      MYSQL_ROOT_PASSWORD: "root"
      PMA_HOST: mysql
    ports:
     - 8081:80
    volumes:
     - /sessions
  
  nginx:
    image: nginx
    container_name: nginx
    networks:
      - net-mysql
    ports:
     - "80:80"
    environment:
     - NGINX_PORT=80

networks: 
  net-mysql: