<?php

use Illuminate\Database\Seeder;

class TaskUserTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        \DB::table('task_user')->delete();
        
        \DB::table('task_user')->insert(array (
            array (
                'item_type' => 1,
                'task_id' => 1,
                'dept_id' => 0,
                'user_id' => 1,
                'receiver_id' => NULL,
                'receive_time' => NULL,
                'report_deadline' => '2018-09-10 17:43:35',
                'report_text' => NULL,
                'report_time' => NULL,
                'audit_text' => NULL,
                'audit_time' => NULL,
                'status' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            array (
                'item_type' => 0,
                'task_id' => 1,
                'dept_id' => 0,
                'user_id' => 2,
                'receiver_id' => NULL,
                'receive_time' => NULL,
                'report_deadline' => '2018-09-10 17:43:35',
                'report_text' => NULL,
                'report_time' => NULL,
                'audit_text' => NULL,
                'audit_time' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            array (
                'item_type' => 0,
                'task_id' => 1,
                'dept_id' => 0,
                'user_id' => 3,
                'receiver_id' => 3,
                'receive_time' => '2018-09-11 18:00:01',
                'report_deadline' => '2018-09-20 17:43:35',
                'report_text' => NULL,
                'report_time' => NULL,
                'audit_text' => NULL,
                'audit_time' => NULL,
                'status' => 2,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            array (
                'item_type' => 0,
                'task_id' => 1,
                'dept_id' => 0,
                'user_id' => 4,
                'receiver_id' => 4,
                'receive_time' => '2018-09-12 18:00:00',
                'report_deadline' => '2018-09-20 17:43:35',
                'report_text' => '上报回复,xxxxxxxx',
                'report_time' => '2018-09-13 20:00:01',
                'audit_text' => NULL,
                'audit_time' => NULL,
                'status' => 3,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            array (
                'item_type' => 0,
                'task_id' => 1,
                'dept_id' => 0,
                'user_id' => 5,
                'receiver_id' => 5,
                'receive_time' => '2018-09-12 18:00:00',
                'report_deadline' => '2018-09-20 17:43:35',
                'report_text' => '上报回复，这条任务是已完成的',
                'report_time' => '2018-09-13 15:30:01',
                'audit_text' => '审核上报,这里是回复的内容',
                'audit_time' => '2018-09-15 10:00:00',
                'status' => 4,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            array (
                'item_type' => 1,
                'task_id' => 2,
                'dept_id' => 3,
                'user_id' => 1,
                'receiver_id' => NULL,
                'receive_time' => NULL,
                'report_deadline' => '2018-09-10 17:43:35',
                'report_text' => NULL,
                'report_time' => NULL,
                'audit_text' => '流转审批，回复的内容',
                'audit_time' => '2018-09-10 20:00:01',
                'status' => 2, // 流转审批，审核通过
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            array (
                'item_type' => 2,
                'task_id' => 2,
                'dept_id' => 0,
                'user_id' => 2,
                'receiver_id' => NULL,
                'receive_time' => NULL,
                'report_deadline' => '2018-09-10 17:43:35',
                'report_text' => NULL,
                'report_time' => NULL,
                'audit_text' => '流转审批，回复的内容',
                'audit_time' => '2018-09-10 20:00:01',
                'status' => 2, // 流转审批，审核通过
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            array (
                'item_type' => 0,
                'task_id' => 2,
                'dept_id' => 0,
                'user_id' => 3,
                'receiver_id' => 3,
                'receive_time' => NULL,
                'report_deadline' => '2018-09-10 17:43:35',
                'report_text' => NULL,
                'report_time' => NULL,
                'audit_text' => NULL,
                'audit_time' => NULL,
                'status' => 0, // 任务流转审批中，所以状态属于未发送
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            array (
                'item_type' => 1,
                'task_id' => 3,
                'dept_id' => 0,
                'user_id' => 1,
                'receiver_id' => NULL,
                'receive_time' => NULL,
                'report_deadline' => '2018-09-10 17:43:35',
                'report_text' => NULL,
                'report_time' => NULL,
                'audit_text' => NULL,
                'audit_time' => NULL,
                'status' => 1, // 流转审批, 待审批
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            array (
                'item_type' => 2,
                'task_id' => 3,
                'dept_id' => 0,
                'user_id' => 2,
                'receiver_id' => NULL,
                'receive_time' => NULL,
                'report_deadline' => '2018-09-10 17:43:35',
                'report_text' => NULL,
                'report_time' => NULL,
                'audit_text' => NULL,
                'audit_time' => NULL,
                'status' => 1, // 流转审批, 待审批
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            array (
                'item_type' => 0,
                'task_id' => 3,
                'dept_id' => 0,
                'user_id' => 3,
                'receiver_id' => 3,
                'receive_time' => NULL,
                'report_deadline' => '2018-09-10 17:43:35',
                'report_text' => NULL,
                'report_time' => NULL,
                'audit_text' => NULL,
                'audit_time' => NULL,
                'status' => 0, // 任务流转审批中，所以状态属于未发送
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            array (
                'item_type' => 1,
                'task_id' => 4,
                'dept_id' => 0,
                'user_id' => 1,
                'receiver_id' => NULL,
                'receive_time' => NULL,
                'report_deadline' => '2018-09-10 17:43:35',
                'report_text' => NULL,
                'report_time' => NULL,
                'audit_text' => '流转审批，回复的内容,不通过的原因',
                'audit_time' => '2018-09-10 20:00:01',
                'status' => 3, // 流转审批，审核不通过
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            array (
                'item_type' => 2,
                'task_id' => 4,
                'dept_id' => 0,
                'user_id' => 2,
                'receiver_id' => NULL,
                'receive_time' => NULL,
                'report_deadline' => '2018-09-10 17:43:35',
                'report_text' => NULL,
                'report_time' => NULL,
                'audit_text' => '流转审批，回复的内容,不通过的原因',
                'audit_time' => '2018-09-10 20:00:01',
                'status' => 3, // 流转审批，审核不通过
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            array (
                'item_type' => 0,
                'task_id' => 4,
                'dept_id' => 0,
                'user_id' => 3,
                'receiver_id' => 3,
                'receive_time' => NULL,
                'report_deadline' => '2018-09-10 17:43:35',
                'report_text' => NULL,
                'report_time' => NULL,
                'audit_text' => NULL,
                'audit_time' => NULL,
                'status' => 0, // 任务流转审批中，所以状态属于未发送
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            array (
                'item_type' => 1,
                'task_id' => 5,
                'dept_id' => 0,
                'user_id' => 2,
                'receiver_id' => NULL,
                'receive_time' => NULL,
                'report_deadline' => NULL,
                'report_text' => NULL,
                'report_time' => NULL,
                'audit_text' => NULL,
                'audit_time' => NULL,
                'status' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            array (
                'item_type' => 0,
                'task_id' => 5,
                'dept_id' => 0,
                'user_id' => 1,
                'receiver_id' => NULL,
                'receive_time' => NULL,
                'report_deadline' => '2018-09-10 17:43:35',
                'report_text' => NULL,
                'report_time' => NULL,
                'audit_text' => NULL,
                'audit_time' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            array (
                'item_type' => 1,
                'task_id' => 6,
                'dept_id' => 0,
                'user_id' => 2,
                'receiver_id' => NULL,
                'receive_time' => NULL,
                'report_deadline' => NULL,
                'report_text' => NULL,
                'report_time' => NULL,
                'audit_text' => NULL,
                'audit_time' => NULL,
                'status' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            array (
                'item_type' => 0,
                'task_id' => 6,
                'dept_id' => 0,
                'user_id' => 1,
                'receiver_id' => 1,
                'receive_time' => '2018-09-11 18:00:01',
                'report_deadline' => '2018-09-20 17:43:35',
                'report_text' => NULL,
                'report_time' => NULL,
                'audit_text' => NULL,
                'audit_time' => NULL,
                'status' => 2,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            array (
                'item_type' => 1,
                'task_id' => 7,
                'dept_id' => 0,
                'user_id' => 3,
                'receiver_id' => NULL,
                'receive_time' => NULL,
                'report_deadline' => NULL,
                'report_text' => NULL,
                'report_time' => NULL,
                'audit_text' => NULL,
                'audit_time' => NULL,
                'status' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            array (
                'item_type' => 0,
                'task_id' => 7,
                'dept_id' => 0,
                'user_id' => 1,
                'receiver_id' => 1,
                'receive_time' => '2018-09-12 18:00:00',
                'report_deadline' => '2018-09-20 17:43:35',
                'report_text' => '上报回复,xxxxxxxx',
                'report_time' => '2018-09-13 20:00:01',
                'audit_text' => NULL,
                'audit_time' => NULL,
                'status' => 3,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            array (
                'item_type' => 0,
                'task_id' => 7,
                'dept_id' => 0,
                'user_id' => 2,
                'receiver_id' => 2,
                'receive_time' => '2018-09-12 18:00:00',
                'report_deadline' => '2018-09-20 17:43:35',
                'report_text' => NULL,
                'report_time' => NULL,
                'audit_text' => NULL,
                'audit_time' => NULL,
                'status' => 2,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            array (
                'item_type' => 1,
                'task_id' => 8,
                'dept_id' => 0,
                'user_id' => 2,
                'receiver_id' => NULL,
                'receive_time' => NULL,
                'report_deadline' => NULL,
                'report_text' => NULL,
                'report_time' => NULL,
                'audit_text' => NULL,
                'audit_time' => NULL,
                'status' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            array (
                'item_type' => 0,
                'task_id' => 8,
                'dept_id' => 0,
                'user_id' => 1,
                'receiver_id' => 1,
                'receive_time' => '2018-09-12 18:00:00',
                'report_deadline' => '2018-09-20 17:43:35',
                'report_text' => '上报回复，这条任务是已完成的',
                'report_time' => '2018-09-13 15:30:01',
                'audit_text' => '审核上报,这里是回复的内容',
                'audit_time' => '2018-09-15 10:00:00',
                'status' => 4,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            array (
                'item_type' => 0,
                'task_id' => 9,
                'dept_id' => 1,
                'user_id' => 1,
                'receiver_id' => 1,
                'receive_time' => '2018-09-12 18:00:00',
                'report_deadline' => NULL,
                'report_text' => NULL,
                'report_time' => NULL,
                'audit_text' => NULL,
                'audit_time' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            array (
                'item_type' => 1,
                'task_id' => 9,
                'dept_id' => 0,
                'user_id' => 2,
                'receiver_id' => NULL,
                'receive_time' => NULL,
                'report_deadline' => NULL,
                'report_text' => NULL,
                'report_time' => NULL,
                'audit_text' => NULL,
                'audit_time' => NULL,
                'status' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            array (
                'item_type' => 0,
                'task_id' => 9,
                'dept_id' => 1,
                'user_id' => 3,
                'receiver_id' => NULL,
                'receive_time' => NULL,
                'report_deadline' => NULL,
                'report_text' => NULL,
                'report_time' => NULL,
                'audit_text' => NULL,
                'audit_time' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            array (
                'item_type' => 0,
                'task_id' => 9,
                'dept_id' => 1,
                'user_id' => 4,
                'receiver_id' => NULL,
                'receive_time' => NULL,
                'report_deadline' => NULL,
                'report_text' => NULL,
                'report_time' => NULL,
                'audit_text' => NULL,
                'audit_time' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            array (
                'item_type' => 3,
                'task_id' => 9,
                'dept_id' => 1,
                'user_id' => 5,
                'receiver_id' => NULL,
                'receive_time' => NULL,
                'report_deadline' => NULL,
                'report_text' => NULL,
                'report_time' => NULL,
                'audit_text' => NULL,
                'audit_time' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            array (
                'item_type' => 0,
                'task_id' => 9,
                'dept_id' => 5,
                'user_id' => 4,
                'receiver_id' => NULL,
                'receive_time' => NULL,
                'report_deadline' => NULL,
                'report_text' => NULL,
                'report_time' => NULL,
                'audit_text' => NULL,
                'audit_time' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            array (
                'item_type' => 0,
                'task_id' => 9,
                'dept_id' => 1,
                'user_id' => 6,
                'receiver_id' => NULL,
                'receive_time' => NULL,
                'report_deadline' => NULL,
                'report_text' => NULL,
                'report_time' => NULL,
                'audit_text' => NULL,
                'audit_time' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            )
        ));
    }
}